bind=h
max_lines=27
max_char=50
max_columns=3
font_scale=100
title_font_scale=75
font_color=HFFFFFF
title_font_color=H808080
font_bind_color=H66FFFF
cursor_font_color=H00FF00
script_font_color=HAAAAFF
margin_x=20
margin_y=20
column_gap=30
